### ISSUE TITLE
Update Link to repository with necessary files

### ISSUE THREAD

**Issue by amanmdesai** [hsf-training/hsf-training-cms-analysis-webpage#10]
Currently https://github.com/awesome-workshop/payload/ is given as a link to the repository containing files (in setup). 

In hsf-training we have https://github.com/hsf-training/hsf-training-cms-analysis which contains all the files, hence it might be good to update the link to hsf repo?

**Comment by klieret** [comment]
You're right :)  That should be changed

**Comment by amanmdesai** [comment]
thanks. will open a PR
